# Generated by Django 2.1.7 on 2019-05-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('color', models.BooleanField(blank=True, null=True)),
                ('film', models.BooleanField(blank=True, null=True)),
                ('film_comp', models.CharField(blank=True, max_length=50, null=True)),
                ('film_stock', models.CharField(blank=True, max_length=50, null=True)),
                ('iso', models.SmallIntegerField(blank=True, null=True)),
                ('aperture', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('shutter', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('focal_length', models.SmallIntegerField(blank=True, null=True)),
                ('aspect_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('camera_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_model', models.CharField(blank=True, max_length=100, null=True)),
                ('lens_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('lens_model', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('taken', models.DateTimeField(blank=True, null=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('photo_source', models.URLField(max_length=300)),
                ('thumbnail_source', models.URLField(max_length=300)),
                ('thumbnail_height', models.SmallIntegerField()),
                ('thumbnail_width', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['taken'],
            },
        ),
        migrations.CreateModel(
            name='PhotoWithTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['tagname'],
            },
        ),
    ]
