# Generated by Django 2.1.7 on 2019-05-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20190518_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagname',
            field=models.SlugField(),
        ),
    ]
