# Generated by Django 2.1.7 on 2019-06-01 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0003_auto_20190531_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together={('owner', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('owner', 'tagname')},
        ),
    ]
