# Generated by Django 2.2.3 on 2019-07-18 23:30

from django.db import migrations, models
import django_boto.s3.storage
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20190709_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumb',
            field=models.ImageField(blank=True, height_field='thumbnail_height', null=True, storage=django_boto.s3.storage.S3Storage(), upload_to=photos.models.upload_thumb_to, width_field='thumbnail_width'),
        ),
    ]
