# Generated by Django 2.2.3 on 2019-07-19 05:34

from django.db import migrations, models
import django_boto.s3.storage
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20190718_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_source',
            field=models.ImageField(storage=django_boto.s3.storage.S3Storage(), upload_to=photos.models.upload_photo_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail_source',
            field=models.ImageField(blank=True, height_field='thumbnail_height', null=True, storage=django_boto.s3.storage.S3Storage(), upload_to=photos.models.upload_thumb_to, width_field='thumbnail_width'),
        ),
    ]
