# Generated by Django 2.1.7 on 2019-03-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('contributors', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('design_source', models.URLField(max_length=300)),
                ('thumbnail_source', models.URLField(max_length=300)),
                ('thumbnail_height', models.SmallIntegerField()),
                ('thumbnail_width', models.SmallIntegerField()),
            ],
        ),
    ]
