# Generated by Django 2.1.7 on 2019-05-31 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20190531_1941'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorited_user', models.BooleanField()),
                ('favorited_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Favorited_Photo', to='photos.Photo')),
                ('favorited_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Favorited_Tag', to='photos.Tag')),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Other_User', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='This_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='favoritephotos',
            name='favorited_photo',
        ),
        migrations.RemoveField(
            model_name='favoritephotos',
            name='this_user',
        ),
        migrations.RemoveField(
            model_name='favoritetags',
            name='favorited_tag',
        ),
        migrations.RemoveField(
            model_name='favoritetags',
            name='this_user',
        ),
        migrations.RemoveField(
            model_name='favoriteusers',
            name='other_user',
        ),
        migrations.RemoveField(
            model_name='favoriteusers',
            name='this_user',
        ),
        migrations.DeleteModel(
            name='FavoritePhotos',
        ),
        migrations.DeleteModel(
            name='FavoriteTags',
        ),
        migrations.DeleteModel(
            name='FavoriteUsers',
        ),
    ]
