// TODO:
export const NEW_PHOTO_SUCCESS = 'NEW_PHOTO_SUCCESS';

//--------------//
// ASYNCHRONOUS //
//--------------//

// SUCCESS
export const TAGS_SUCCESS = 'TAGS_SUCCESS';
export const ALL_TAGS_SUCCESS = 'ALL_TAGS_SUCCESS';
export const RELATIONS_SUCCESS = 'RELATIONS_SUCCESS';
export const PHOTOS_SUCCESS = 'PHOTOS_SUCCESS';
export const ALL_PHOTOS_SUCCESS = 'ALL_PHOTOS_SUCCESS';

export const AUTHENTICATION_SUCCESS= 'AUTHENTICATION_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS';
export const VIEWING_USER_SUCCESS = 'VIEWING_USER_SUCCESS';


// LOADING
export const TAGS_LOADING = 'TAGS_LOADING';
export const ALL_TAGS_LOADING = 'ALL_TAGS_LOADING';
export const RELATIONS_LOADING = 'RELATIONS_LOADING';
export const PHOTOS_LOADING = 'PHOTOS_LOADING';
export const ALL_PHOTOS_LOADING = 'ALL_PHOTOS_LOADING';

export const AUTHENTICATION_LOADING = 'AUTHENTICATION_LOADING';
export const ALL_USERS_LOADING = 'ALL_USERS_LOADING';

// FAILURE
export const TAGS_FAILURE = 'ALL_TAGS_FAILURE';
export const ALL_TAGS_FAILURE = 'ALL_TAGS_FAILURE';
export const RELATIONS_FAILURE = 'RELATIONS_FAILURE';
export const PHOTOS_FAILURE = 'PHOTOS_FAILURE';
export const ALL_PHOTOS_FAILURE = 'ALL_PHOTOS_FAILURE';

export const AUTHENTICATION_FAILURE= 'AUTHENTICATION_FAILURE';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const ALL_USERS_FAILURE = 'ALL_USERS_FAILURE';
export const VIEWING_USER_FAILURE = 'VIEWING_USER_FAILURE';
//-------------//
// SYNCHRONOUS //
//-------------//
export const SET_TAGS = 'SET_TAGS';
